---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: evil-chat.kubernetes.docker.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}-rails
          servicePort: 3000
      - path: /packs
        backend:
          serviceName: {{ .Chart.Name }}-assets
          servicePort: 80